name: agrimotor
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  dio: ^4.0.6
  fresh_dio: ^0.3.2
  equatable: ^2.0.5
  flutter_secure_storage: ^6.0.0
  quiver: ^3.2.1
  url_launcher: ^6.1.5
  permission_handler: ^10.2.0
  geolocator: ^9.0.2
  connectivity_plus: ^3.0.6
  go_router: ^5.2.4
  app_links: ^3.4.2
  version: ^3.0.2
  package_info_plus: ^4.0.0
  device_info_plus: ^9.0.0
  firebase_remote_config: ^4.0.1
  shared_preferences: ^2.0.15
  retrofit: ^3.3.1
  flutter_screenutil: ^5.8.1
  hexcolor: ^3.0.1
  pull_to_refresh: ^2.0.0
  bot_toast: ^4.0.3
  get_it: ^7.2.0
  flutter_local_notifications: ^9.9.1
  firebase_messaging: ^14.4.1
  event_bus: ^2.0.0
  google_fonts: ^4.0.4
  showcaseview: ^2.0.3
  flutter_svg: ^1.1.4

  #
  # firebase_analytics: ^10.4.3
  # firebase_crashlytics: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  mockito: ^5.3.0
  retrofit_generator: ^4.2.0
  flutter_launcher_icons: ^0.12.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
